sudo: required # 관리자 권한갖기

language: generic # 언어 (플랫폼) 선택

services: # 도커 환경 구성
  - docker

before_install: # 스크립트를 실행할 수 있는 환경 구성
  - echo "start Creating an image with dockerfile"
  - docker build -t jamlee/react-app -f Dockerfile .

script: # 실행할 스크립트 ( 테스트 실행 )
  - docker run -e CI=true jamlee/react-app npm run test -- --coverage

#after_success:  # 테스트 성공 후 할 일
#  - echo "Test Success"

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-043950910884"
  bucket_path: "docker-react-app"
  on: 
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY


